config/routes.rb
Rottenpotatoes::Application.routes.draw do
    resources :users, only: [:create]
    resources :sessions, only: [:new, :create]
    resources :entitlements, only: [:create]
    resources :entitlements do
      post 'delete_viewer', on: :collection
    end
    resources :movies
    resources :professors
    get '/profile', to: 'users#profile', as: 'user_profile'
    delete '/sessions/clear', to: 'sessions#clear', as: 'clear_session'
    root :to => redirect('/sessions/new')
  
    resources :teaching_assistants do
      get 'new_office_hour', on: :collection
      post 'create_office_hour', on: :collection
      get 'edit_office_hour', on: :collection
      patch 'update', on: :member
    end
  
    resources :calendars, only: [:index, :destroy, :edit, :update] do
        get 'next_week', on: :collection
        get 'prev_week', on: :collection
    end
  end
  

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :calendars
end

app/controllers/users_controller.rb
require 'set'

class UsersController < ApplicationController

    skip_before_action :require_login, only: [:create]

    def profile

        @viewable_courses = Set.new
        @calendars = Set.new(current_user.calendars)

        @entitlements = Entitlement.where(uni: current_user.uni)
        @entitlements.each do |entitlement|
            potential_course = Course.find_by(courseName: entitlement.courseName)
            if not potential_course.nil?
                @viewable_courses << potential_course
            end
        end
        @all_course_list = Course.pluck(:courseName)
    end

    def create
        existing_user = User.find_by(uni: user_params[:uni])
        if existing_user
            flash[:warning] = "Inputted UNI already has an account. Please log in instead."
            redirect_to new_session_path
        else
            new_user = User.create(user_params)
            session[:user_uni] = new_user.uni
            redirect_to user_profile_path
        end
    end
  
    private 
    def user_params
      params.require(:user).permit(:uni, :name, :password, :is_professor)
    end
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/profile.html.erb
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="app/assets/stylesheets/profile.scss">
</head>
<body class="profileclass">
<div class="container rounded bg-white mt-5 mb-5 newsize">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
            <%= image_tag "hourglass.png", :class => 'rounded-circle pic', :width=>"150px" %>
              <span class="font-weight-bold"><%= content_tag :h1, "#{current_user.name}" %></span><span class="text-black-50"><%= "#{current_user.uni}" %></span><span> </span>
            </div>
            <% if current_user.is_professor == true %>
              <%= link_to 'Create a New Course', professors_path, :class => 'btn btn-primary leftfloat' %>
            <% end %>
            </br>
            </br>
            <% if @entitlements.any? { |entitlement| ['Prof', 'TA'].include?(entitlement.role) } %>
              <%= link_to 'Create New Office Hours', new_office_hour_teaching_assistants_path, :class => 'btn btn-primary leftfloat' %>  
              </br>
              </br>   
              <%= link_to 'Edit Current Office Hours', edit_office_hour_teaching_assistants_path, :class => 'btn btn-primary leftfloat' %>
            <% end %>
            </br>
            </br>
            </br>
            </br>
            </br>
            <%= link_to "Sign out", clear_session_path, method:"delete", :class => 'btn btn-primary leftfloat' %>
        </div>
        <div class="col-md-5 border-right">
        <div class="d-flex flex-column align-items-center text-center p-3 py-5">
        <span class="highlight"><%= content_tag :h3, "Add a new course to your Schedule" %></span>
          <%= form_tag entitlements_path, method: :post, :class => 'form' do %>
            <%= label :entitlement, :courseName, 'Course Name', :class => 'col-form-label'  %>
            <%= select :entitlement, :courseName, @all_course_list, { prompt: 'Select a Course' }, class: 'form-control' %>
            <%= text_field :entitlement, :role, value: 'Viewer', :type => 'hidden' %>
            </br>
            <%= submit_tag "Add New Viewable Course", :class => 'btn btn-primary leftfloat' %>
          <% end %>

          </br></br></br>
          <% if @entitlements.any? { |entitlement| ['Prof', 'TA'].include?(entitlement.role) } %>
          <%= content_tag :h3, "Your Office Hour Slots", :class => 'highlight' %>
          </br>
          <table class="table table-striped col-md-12" id="movies">
            <thead>
              <tr>
                <th>Course Name</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Location</th>
              </tr>
            </thead>
            <tbody>
              <% @calendars.each do |slot| %>
                <tr>
                  <td>
                    <%= slot.courseName %>
                  </td>
                  <td>
                    <%= slot.start_time %>
                  </td>
                  <td>
                    <%= slot.end_time %>
                  </td>
                  <td>
                    <%= slot.location %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </br></br></br>
        <% end %>

        </div>
        </div>
        <div class="col-md-4">
        <div class="d-flex flex-column align-items-center text-center p-3 py-5">
        <%= content_tag :h3, "Your Viewable Courses", :class => 'highlight'%>
        </br>
        <table class="table table-striped col-md-12" id="movies">
          <thead>
            <tr>
              <th>Course Name</th>
              <th>Course Description</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @viewable_courses.each do |course| %>
              <tr>
                <td>
                  <%= course.courseName %>
                </td>
                <td>
                  <%= course.courseDescription %>
                </td>
                <td>
                <%= form_tag delete_viewer_entitlements_path, method: :post, :class => 'form' do %>
                  <%= text_field :entitlement, :courseName, value: course.courseName, :type => 'hidden' %>
                  <%= submit_tag "Remove", class: 'btn btn-danger btn-secondary leftfloat' %>
                <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to 'View Schedule', calendars_path, :class => 'btn btn-primary' %>
        </div>
        </div>
    </div>
</div>
</div>
</div>
</body>
</html>

</br></br></br>
</br></br></br>
</br></br></br>
</br></br></br>