config/routes.rb
Rottenpotatoes::Application.routes.draw do
    resources :users, only: [:create]
    resources :sessions, only: [:new, :create]
    resources :entitlements, only: [:create]
    resources :entitlements do
      post 'delete_viewer', on: :collection
    end
    resources :movies
    resources :professors
    get '/profile', to: 'users#profile', as: 'user_profile'
    delete '/sessions/clear', to: 'sessions#clear', as: 'clear_session'
    root :to => redirect('/sessions/new')
  
    resources :teaching_assistants do
      get 'new_office_hour', on: :collection
      post 'create_office_hour', on: :collection
      get 'edit_office_hour', on: :collection
      patch 'update', on: :member
    end
  
    resources :calendars, only: [:index, :destroy, :edit, :update] do
        get 'next_week', on: :collection
        get 'prev_week', on: :collection
    end
  end
  

app/models/calendar.rb
# app/models/calendar.rb
class Calendar < ActiveRecord::Base
  validates :courseName, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :repeated_weeks, numericality: { greater_than_or_equal_to: 0 }
  validates :location, presence: true
end

app/controllers/calendars_controller.rb
require 'date'
require 'active_support/time'

class CalendarsController < ApplicationController

    def index
      if not params.key?(:year)
        current_sunday = get_last_sunday_date(Date.today)
      else
        current_sunday = Date.new(params[:year].to_i, params[:month].to_i, params[:day].to_i)
      end

      @year = current_sunday.year
      @month = current_sunday.month
      @day = current_sunday.day 
      
      dtstart = DateTime.new(@year, @month, @day)
      dtend = dtstart + 7
      
      @all_days = []
      for i in 0..6
        @all_days.append({wday: days_map[i], date: (dtstart + i).strftime('%m/%d/%Y')})
      end

      # The pluck method works for application usage here, but runs into issues with Rspec testing due to our old Ruby version. 
      # Simiplified to a for loop for now
      my_entitlements = Entitlement.where(uni: current_user.uni)
      classes = []
      my_entitlements.each do |entitlement|
        if not entitlement.courseName.nil?
          classes << entitlement.courseName
        end
      end

      @calendars = Calendar.where(courseName: classes).where('start_time >= ? AND end_time < ?', dtstart, dtend).order(:start_time)
      @calendars = @calendars.map do |calendar|
        new_calendar = OpenStruct.new(calendar.attributes)
        new_calendar.wday = idx_to_day(calendar.start_time.wday)
        new_calendar
      end

      @calendar_edits = CalendarEdit.where(courseName: classes)
                        .where('start_time >= ? AND end_time < ?', dtstart, dtend)
                        .order(:update_time).group_by(&:courseName)
      @edit_description = method(:edit_description)
    end

    def destroy
      @calendar = Calendar.find(params[:id])
      create_calendar_deletion(@calendar)
      @calendar.destroy
      redirect_to edit_office_hour_teaching_assistants_path, notice: 'Office hour was successfully deleted.'
    end

    def create_calendar_deletion(calendar)
        CalendarEdit.create(
          courseName: calendar.courseName,
          start_time: calendar.start_time,
          end_time: calendar.end_time,
          location: calendar.location,
          user_id: calendar.user_id,
          edit_type: CalendarEdit.edit_types[:deletion], # Assuming you have an enum in CalendarEdit for edit_type
          update_time: DateTime.now.in_time_zone("EST")
        )
    end

    def edit_description(edit)
      user = User.find(edit.user_id).uni
      
      u_time = tFmt(edit.update_time.in_time_zone('EST'), 'DT')
      s_day = tFmt(edit.start_time, 'D')
      s_time = tFmt(edit.start_time, 'T')
      e_time = tFmt(edit.end_time, 'T')
      case edit.edit_type
      when 'update_deletion'
        "[#{u_time}] #{user}: Not holding OH originally scheduled on #{s_day} from #{s_time} to #{e_time} at #{edit.location}."
      when 'update_addition'
        "[#{u_time}] #{user}: Conducting replacement OH on #{s_day} from #{s_time} to #{e_time} at #{edit.location}"
      when 'deletion'
        "[#{u_time}] #{user}: Cancelling OH on #{s_day} from #{s_time} to #{e_time} at #{edit.location}"
      end
    end

    def tFmt(t, mode)
      case mode
      when 'DT'
        t.strftime('%m/%d/%Y %H:%M')
      when 'D'
        t.strftime('%b %d (%A)')
      when 'T'
        t.strftime('%H:%M')
      end
    end

    def edit
      @calendar = Calendar.find(params[:id])
    end

    def next_week
        year = params[:year].to_i
        month = params[:month].to_i
        day = params[:day].to_i

        next_date = Date.new(year, month, day) + 7
        redirect_to calendars_path({year: next_date.year, month: next_date.month, day: next_date.day})
    end

    def prev_week
        year = params[:year].to_i
        month = params[:month].to_i
        day = params[:day].to_i
        
        prev_date = Date.new(year, month, day) - 7
        redirect_to calendars_path({year: prev_date.year, month: prev_date.month, day: prev_date.day})
    end

    def get_last_sunday_date(date)
        date - date.wday
    end

    def idx_to_day(idx)
        days_map[idx]
    end
    def days_map
        {0 => "Sunday", 
        1 => "Monday", 
        2 => "Tuesday",
        3 => "Wednesday",
        4 => "Thursday",
        5 => "Friday",
        6 => "Saturday"}
    end
end

app/views/calendars/edit.html.erb
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="app/assets/stylesheets/profile.scss">
</head>
<body class="profileclass">
<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
            <%= image_tag "hourglass.png", :class => 'rounded-circle pic', :width=>"150px" %>
              <span class="font-weight-bold"><%= content_tag :h1, "#{current_user.name}" %></span><span class="text-black-50"><%= "#{current_user.uni}" %></span><span> </span>
            </div>
            <% if current_user.is_professor == true %>
              <%= link_to 'Create a New Course', professors_path, :class => 'btn btn-primary leftfloat' %>
            <% end %>
            </br>
            </br>
            
              <%= link_to 'Create New Office Hours', new_office_hour_teaching_assistants_path, :class => 'btn btn-primary leftfloat' %>  
              </br>
              </br>   
              <%= link_to 'Edit Current Office Hours', edit_office_hour_teaching_assistants_path, :class => 'btn btn-primary leftfloat' %>
            </br>
            </br>
            <%= link_to "Sign out", clear_session_path, method:"delete", :class => 'btn btn-primary leftfloat' %>
        </div>
        <div class="col-md-9 border-right">
        <div class="d-flex flex-column align-items-center text-center p-3 py-5">
          <h1 class="highlight">Edit Office Hours</h1>

          </br>

          <%= form_for @calendar, url: teaching_assistant_path(@calendar), method: :patch do |form| %>
            <% if @calendar.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>
                <ul>
                  <% @calendar.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
          
            <div class="field">
              <span class="form-group form-inline">
                <%= form.label :start_time %>
                <%= form.datetime_select :start_time, :default => DateTime.new(DateTime.now.year, DateTime.now.month, DateTime.now.day, DateTime.now.hour, 0), :ampm => true, :minute_step => 15%>
              </span>
            </div>
          
            <div class="field">
              <span class="form-group form-inline">
                <%= form.label :end_time %>
                <%= form.datetime_select :end_time, :default => DateTime.new(DateTime.now.year, DateTime.now.month, DateTime.now.day, DateTime.now.hour, 0), :ampm => true, :minute_step => 15%>
              </span>
            </div>
          
            <div class="field">
              <%= form.label :repeated_weeks, "Number of Repeated Weeks" %>
              <%= form.number_field :repeated_weeks, class: 'form-control' %>
            </div>

            <div class="field">
            <%= form.label :location %>
            <%= form.text_field :location, class: 'form-control' %>
          </div>
          
            <div class="actions">
              <%= form.submit 'Update Calendar', :class => 'btn btn-primary' %>
            </div>
          <% end %>
        </div>
        </div>
        <div class="col-md-0">
        <div class="d-flex flex-column align-items-center text-center p-3 py-5">
        
        </div>
        </div>
        <%= link_to 'Return to Profile', user_profile_path, :class => 'btn btn-primary leftfloat col-3' %>
    </div>
</div>
</div>
</div>
</body>
</html>

</br></br></br>
</br>

app/views/calendars/index.html.erb
<!-- app/views/calendars/index.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>Calendar</title>
  <link rel="stylesheet" href="app/assets/stylesheets/profile.scss">
  <style>
    .update_deletion { color: #295285; }
    .update_addition {color: #36853d; }
    .deletion { color: #783d3d; }
    .container {
      width: 85%;
      display: grid;
      grid-template-areas: ". days" "time calendar";
    }

    ol {
      list-style: none;
      margin: 0;
      padding: 0;
      text-align: center;
    }

    ol.time {
      grid-area: time;
      display: grid;
      grid-template-rows: repeat(24, 1fr); # Total 24 rows for 24 different hour slots
    }

    ol.time > li {
      display: flex;
      align-items: flex-end;
      justify-content: flex-end;
      border-bottom: 2px dotted #573b8a;
    }

    ol.time > li > time {
      padding: 3px;
      line-height: 1;
      font-size: small;
    }

    ol.days {
      grid-area: days;
      display: grid;
      grid-template-columns: repeat(7, 1fr); # Total 7 columns for 7 days
    }

    ol.calendar {
      grid-area: calendar;
      display: grid;
      gap: 1.4px;
      grid-template: repeat(4*24, 1fr)/repeat(7, 1fr); # 96 rows for 24 hours, 4 15-min segments to each individual hour. 7 columns for 7 days
      grid-auto-flow: column;
      background-color: #e1e2e6;
      border: 2px solid #573b8a;
      border-radius: 2px;
    }

    ol.calendar > li {
      height: 35px;
      grid-column: var(--column);
      grid-row: var(--row);
      background-color: white;
    }

    <% 24.times do |i|%>
      ol.calendar li:nth-child(24n+<%=i+1%>) {
        --row: <%= (4*i)+1 %> / span 4; # Set the row of each part of our calendar (based on number of hours in calendar)
      }
    <% end %>

    <% 7.times do |i|%>
      ol.calendar li:nth-child(n+<%= i*24 + 1%>):nth-child(-n+<%= (i+1)*24%>) {
        --column: <%= i+1 %>; # Set the column of each part of our calendar (based on number of days in calendar)
      }
    <% end %>

    .task {
      z-index: var(--z-index);
      grid-column: var(--column);
      grid-row: var(--row);
      background-color: var(--color);
      border-radius: 4px;
      margin: 1px 1px 1px 1px;
      opacity: 0.7
    }

    .task:hover{
      opacity: 1.0;
      font-weight: bold;
    }

    .task:hover div{
      font-weight: normal;
      display: inline;
    }

    .task p {
      margin: 0;
      padding: 2px;
      font-size: 1vw;
      position: absolute;
      background-color:black;
      color:white;
      border-radius: 4px;
    }

    .task div {
      margin-left: 100px;
      display: none;
      margin: 0;
      white-space: pre-line;
      padding: 2px;
      font-size: 1vw;
      position: absolute;
      right: 20px;
      top: 600px;
      width: 15%;
      background-color: black;
      color: white;
      border: 1px solid black;
      border-radius: 10px;
    }

    .btn {
      margin: 10px;
    }
  </style>
</head>

<body class="profileclass">
<div class="container rounded bg-white mt-5 mb-5 calendarsize">
    <div class="row">
        <div class="col-md-2 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
            <%= image_tag "hourglass.png", :class => 'rounded-circle pic', :width=>"150px" %>
              <span class="font-weight-bold"><%= content_tag :h1, "#{current_user.name}" %></span><span class="text-black-50"><%= "#{current_user.uni}" %></span><span> </span>
            </div>

            <%= link_to 'Return to Profile', user_profile_path, :class => 'btn btn-primary ' %>
            </br>
            <%= link_to "Sign out", clear_session_path, method:"delete", :class => 'btn btn-primary leftfloat' %>
        </div>
        <div class="col-md-10 border-right">
        <div class="d-flex flex-column align-items-center text-center p-3 py-5"> 
        <h1><span class="highlight">Course Office Hour Calendars</span></h1>

          <div class="block_container">
          <div class="bloc2 previousweek">
          <%= link_to 'Prev Week', prev_week_calendars_path(year: @year, month: @month, 
                                                              day: @day ), :class => 'btn btn-primary leftfloat' %>
          </div>
          
          <div class="bloc1 nextweek"><%= link_to 'Next Week', next_week_calendars_path(year: @year, month: @month, 
                                                                day: @day ), :class => 'btn btn-primary rightfloat' %>
          </div>
          </div>                                               
          </br></br></br>
          
          <section class="container">
            <ol class="days">
              <% @all_days.each do |day| %>
                <li><%= "#{day[:wday]} #{day[:date]} " %></li>
              <% end %>
            </ol>
            <ol class="time">
              <% (1..24).each do |hour| %>
                <li>
                  <time><%= (hour % 12 != 0 ? hour % 12 : 12).to_s + (hour >= 12 && hour != 24? ' pm' : ' am') %></time>
                </li>
              <% end %>
            </ol>
            <ol class="calendar">
              <% (@all_days.length * 24).times do %>
                <li></li>
              <% end %>
              <% @calendars.each_with_index do |event, index| %>
                <% random_gen = Random.new(Course.find_by(courseName: event.courseName).id) %>
                <% red = random_gen.rand(200) + 50 %>
                <% blue = random_gen.rand(200) + 50 %>
                <% color = '#' + red.to_s(16) + '00' + blue.to_s(16) %>
                <% converted_wday = event.start_time.wday + 1 %>
                <% start_row = (event.start_time.hour * 4 + event.start_time.min.div(15)) + 1 %>
                <% span = event.end_time.wday == event.start_time.wday ? (event.end_time.hour * 4 + event.end_time.min.div(15)) + 1 - start_row : 96 - start_row + 1 %>
                <section class="task"  
                style="--z-index: <%= index %>; --column: <%= converted_wday %>; --row: <%= start_row %> / span <%= span %>; --color: <%= color %>;">
                  <p><%= "#{event.courseName} OH" %></p>
                  <div><%= "Organizer: #{User.find(event.user_id).uni} \n Course: #{event.courseName} \n Time: #{event.start_time.strftime('%l:%M%p')} to #{event.end_time.strftime('%l:%M%p')} \n Location: #{event.location}" %></div>
                </section>
              <% end %>
            </ol>
          </section>
         
          <br><br><h3><span>Updates for the week</span></h3>
        </div>  

        <div class="d-flex flex-column align-items-left text-left p-5 py-5" style="margin-top: -50px;">  
          <% @calendar_edits.each do |course_name, edits| %> 
              <h5><span> <%= course_name %> </span></h5>

              <% edits.each do |edit| %>
                <span class="<%= edit.edit_type %>">
                <strong><%= @edit_description.call(edit) %></strong>
                </span>
              <% end %>
              <hr>
          <% end %>
         </div>
      </div>
</div>
</div>
</body>
</html>

</br></br></br>
</br></br></br>
</br></br></br>
</br></br></br>

<body>