config/routes.rb
Rottenpotatoes::Application.routes.draw do
    resources :users, only: [:create]
    resources :sessions, only: [:new, :create]
    resources :entitlements, only: [:create]
    resources :entitlements do
      post 'delete_viewer', on: :collection
    end
    resources :movies
    resources :professors
    get '/profile', to: 'users#profile', as: 'user_profile'
    delete '/sessions/clear', to: 'sessions#clear', as: 'clear_session'
    root :to => redirect('/sessions/new')
  
    resources :teaching_assistants do
      get 'new_office_hour', on: :collection
      post 'create_office_hour', on: :collection
      get 'edit_office_hour', on: :collection
      patch 'update', on: :member
    end
  
    resources :calendars, only: [:index, :destroy, :edit, :update] do
        get 'next_week', on: :collection
        get 'prev_week', on: :collection
    end
  end
  

app/controllers/teaching_assistants_controller.rb
class TeachingAssistantsController < ApplicationController
  before_action only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user, only: [:new_office_hour, :create_office_hour]

  def new_office_hour
    @your_classes = Entitlement.where({uni: current_user.uni, role: ["TA", "Prof"]}).map(&:courseName)
    @calendar = Calendar.new

    @entitlements = Entitlement.where(uni: current_user.uni, role: ["TA", "Prof"])
  end

  def create_office_hour
    if not valid_calendar
      flash[:warning] = 'All calendar events must end on the same day and strictly after the start time'
      redirect_to new_office_hour_teaching_assistants_path
    elsif
      @calendar = current_user.calendars.build(calendar_params)
      @entitlements = Entitlement.where(uni: current_user.uni, role: ["TA", "Prof"])
      if @calendar.save
        if @calendar.repeated_weeks.positive?
          start_time = @calendar.start_time.advance(weeks: 1)
          end_time = @calendar.end_time.advance(weeks: 1)
          repeated_weeks = @calendar.repeated_weeks
          location = @calendar.location
    
          while start_time <= repeated_weeks.weeks.from_now(@calendar.start_time)
            new_calendar = current_user.calendars.build(
              courseName: @calendar.courseName,
              start_time: start_time,
              end_time: end_time,
              repeated_weeks: @calendar.repeated_weeks,
              location: @calendar.location
            )
            new_calendar.save
            start_time = start_time.advance(weeks: 1)
            end_time = end_time.advance(weeks: 1)
          end
          redirect_to user_profile_path, notice: 'Office hours were successfully added.'
        else
          redirect_to user_profile_path, notice: 'Office hour was successfully added.'
        end
      end
    end
  end

  def edit_office_hour
    @courseNames = current_user.calendars.uniq(&:courseName).map(&:courseName).to_set
    if params[:courseName].present?
      @filtered_calendars = current_user.calendars.select { |calendar| calendar.courseName == params[:courseName] }
    else
      @filtered_calendars = current_user.calendars
    end
    @entitlements = Entitlement.where(uni: current_user.uni, role: ["TA", "Prof"])
  end

  def update
    @calendar = Calendar.find(params[:id])

    time = DateTime.now.in_time_zone("EST")
    calendar_update_del = get_calendar_update(@calendar, time, :update_deletion) 
    if not valid_calendar
      flash[:warning] = 'All calendar events must end on the same day and strictly after the start time'
      redirect_to edit_calendar_path(@calendar)
    elsif @calendar.update(calendar_params)  
      calendar_update_add = get_calendar_update(@calendar, time, :update_addition)
      calendar_update_del.save
      calendar_update_add.save 
      redirect_to edit_office_hour_teaching_assistants_path, notice: 'Office hour was successfully updated.'
    end
  end
  
  def get_calendar_update(calendar, time, op)
    CalendarEdit.new(
      courseName: calendar.courseName,
      start_time: calendar.start_time,
      end_time: calendar.end_time,
      location: calendar.location,
      user_id: calendar.user_id,
      edit_type: CalendarEdit.edit_types[op], # Assuming you have an enum in CalendarEdit for edit_type
      update_time: time
    )
  end

  private
  def calendar_params
    params.require(:calendar).permit(:courseName, :start_time, :end_time, :repeated_weeks, :location)
  end

  private
  def valid_calendar
    params = calendar_params
    any_field_missing = params["start_time(1i)"].nil? or params["start_time(2i)"].nil? or params["start_time(3i)"].nil? or params["start_time(4i)"].nil? or params["start_time(5i)"].nil? or params["end_time(1i)"].nil? or params["end_time(2i)"].nil? or params["end_time(3i)"].nil? or params["end_time(4i)"].nil? or params["end_time(5i)"].nil?
    if any_field_missing
      return false
    end
    start_year = params["start_time(1i)"].to_i
    start_month = params["start_time(2i)"].to_i
    start_day = params["start_time(3i)"].to_i
    start_hour = params["start_time(4i)"].to_i
    start_minute = params["start_time(5i)"].to_i
    end_year = params["end_time(1i)"].to_i
    end_month = params["end_time(2i)"].to_i
    end_day = params["end_time(3i)"].to_i
    end_hour = params["end_time(4i)"].to_i
    end_minute = params["end_time(5i)"].to_i
    Date.new(start_year, start_month, start_day) === Date.new(end_year, end_month, end_day) and DateTime.new(start_year, start_month, start_day, start_hour, start_minute) < DateTime.new(end_year, end_month, end_day, end_hour, end_minute)
  end
end

app/views/teaching_assistants/edit_office_hour.html.erb
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="app/assets/stylesheets/profile.scss">
</head>
<body class="profileclass">
<div class="container rounded bg-white mt-5 mb-5 newsize">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
            <%= image_tag "hourglass.png", :class => 'rounded-circle pic', :width=>"150px" %>
              <span class="font-weight-bold"><%= content_tag :h1, "#{current_user.name}" %></span><span class="text-black-50"><%= "#{current_user.uni}" %></span><span> </span>
            </div>
            <% if current_user.is_professor == true %>
              <%= link_to 'Create a New Course', professors_path, :class => 'btn btn-primary leftfloat' %>
            <% end %>
            </br>
            </br>
            <% if @entitlements.any? { |entitlement| ['Prof', 'TA'].include?(entitlement.role) } %>
              <%= link_to 'Create New Office Hours', new_office_hour_teaching_assistants_path, :class => 'btn btn-primary leftfloat' %>  

            <% end %>
            </br>
            </br>
            </br>
            </br>
            <%= link_to "Sign out", clear_session_path, method:"delete", :class => 'btn btn-primary leftfloat' %>
        </div>
        <div class="col-md-9 border-right">
        <div class="d-flex flex-column align-items-center text-center p-3 py-5">
          <div class="block_container">

            <div class="bloc1">
              <%= content_tag :h3, "Filter by Course", :class => 'highlight' %>
              </br>
              <%= form_tag({ controller: 'teaching_assistants', action: 'edit_office_hour' }, method: :get) do %>
              <%= label_tag :courseName, 'Select Course:' %>
              <%= select_tag(:courseName, options_for_select(@courseNames), { prompt: 'Select a Course' }) %>
            </div>  
            &nbsp&nbsp&nbsp&nbsp&nbsp
            <div class="bloc2"><%= submit_tag 'Filter', :class => 'btn btn-primary' %></div>
            <% end %>
          </div>
            <%= content_tag :h3, "Filtered Office Hour Slots" %>
            <table class="table table-striped col-md-12" id="office_hours">
              <thead>
                <tr>
                  <th>Course Name</th>
                  <th>Start Time</th>
                  <th>End Time</th>
                  <th>Location</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                <% @filtered_calendars.each do |slot| %>
                  <tr>
                    <td>
                      <%= slot.courseName %>
                    </td>
                    <td>
                      <%= slot.start_time %>
                    </td>
                    <td>
                      <%= slot.end_time %>
                    </td>
                    <td>
                      <%= slot.location %>
                    </td>
                    <td>
                      <%= link_to 'Edit', edit_calendar_path(slot), class: 'btn btn-warning' %>
                      <%= link_to 'Delete', calendar_path(slot), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
        </div>
        </div>
        <div class="col-md-0">
        <div class="d-flex flex-column align-items-center text-center p-3 py-5">
        
        </div>
        </div>
        <%= link_to 'Return to Profile', user_profile_path, :class => 'btn btn-primary leftfloat col-3' %>
    </div>
</div>
</div>
</div>
</body>
</html>



</br></br></br>
</br></br></br>
</br>

app/views/teaching_assistants/index.html.erb
<!-- app/views/teaching_assistants/index.html.erb -->
<h1>Teaching Assistants</h1>

<ul>
  <% @teaching_assistants.each do |teaching_assistant| %>
    <li><%= teaching_assistant.name %> - <%= teaching_assistant.uni %> - <%= teaching_assistant.courseName %></li>
  <% end %>
</ul>

app/views/teaching_assistants/new_office_hour.html.erb
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="app/assets/stylesheets/profile.scss">
</head>
<body class="profileclass">
<div class="container rounded bg-white mt-5 mb-5">
    <div class="row">
        <div class="col-md-3 border-right">
            <div class="d-flex flex-column align-items-center text-center p-3 py-5">
            <%= image_tag "hourglass.png", :class => 'rounded-circle pic', :width=>"150px" %>
              <span class="font-weight-bold"><%= content_tag :h1, "#{current_user.name}" %></span><span class="text-black-50"><%= "#{current_user.uni}" %></span><span> </span>
            </div>
            <% if current_user.is_professor == true %>
              <%= link_to 'Create a New Course', professors_path, :class => 'btn btn-primary leftfloat' %>
            <% end %>
            </br>
            </br>
            <% if @entitlements.any? { |entitlement| ['Prof', 'TA'].include?(entitlement.role) } %>
              
              </br>   
              <%= link_to 'Edit Current Office Hours', edit_office_hour_teaching_assistants_path, :class => 'btn btn-primary leftfloat' %>
            <% end %>
            </br>
            </br>
            <%= link_to "Sign out", clear_session_path, method:"delete", :class => 'btn btn-primary leftfloat' %>
        </div>
        <div class="col-md-9 border-right">
        <div class="d-flex flex-column align-items-center text-center p-3 py-5">
        <%= content_tag :h3, "Create New Office Hours", :class => 'highlight'  %>  
        <%= form_for @calendar, url: create_office_hour_teaching_assistants_path, local: true do |form| %>
            <% if @calendar.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@calendar.errors.count, "error") %> prohibited this calendar from being saved:</h2>
                <ul>
                  <% @calendar.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <br>
            <div class="field">
              <%= form.label :courseName %>
              <%= form.select :courseName, options_for_select(@your_classes), {}, class: 'form-control' %>
            </div>
          
            <br>
            <div class="field">
              <span class="form-group form-inline">
                <%= form.label :start_time %>
                <%= form.datetime_select :start_time, :default => DateTime.new(DateTime.now.year, DateTime.now.month, DateTime.now.day, DateTime.now.hour, 0), :ampm => true, :minute_step => 15%>
              </span>
            </div>
          
            <div class="field">
              <span class="form-group form-inline">
                <%= form.label :end_time %>
                <%= form.datetime_select :end_time, :default => DateTime.new(DateTime.now.year, DateTime.now.month, DateTime.now.day, DateTime.now.hour, 0), :ampm => true, :minute_step => 15%>
              </span>
            </div>
          
              </br>
            <div class="field">
              <%= form.label :repeated_weeks, "Number of Repeated Weeks" %>
              <%= form.number_field :repeated_weeks, class: 'form-control', min: "0" %>
            </div>

            <div class="field">
              <%= form.label :location %>
              <%= form.text_field :location, class: 'form-control' %>
            </div>
          
            <%= form.submit 'Create Calendar', :class => 'btn btn-primary'%>
          <% end %>
        </div>
        </div>
        <div class="col-md-0">
        <div class="d-flex flex-column align-items-center text-center p-3 py-5">
        
        </div>
        </div>
        <%= link_to 'Return to Profile', user_profile_path, :class => 'btn btn-primary leftfloat col-3' %>
    </div>
</div>
</div>
</div>
</body>
</html>



</br></br></br>
</br></br></br>
</br>

app/views/teaching_assistants/show.html.erb
<!-- app/views/teaching_assistants/show.html.erb -->
<h1>Teaching Assistant Details</h1>

<p><strong>Name:</strong> <%= @teaching_assistant.name %></p>
<p><strong>Uni:</strong> <%= @teaching_assistant.uni %></p>
<p><strong>Course Name:</strong> <%= @teaching_assistant.courseName %></p>

<%= link_to 'Back', teaching_assistants_path %>